### ISSUE TITLE
Bounding Box Generator gives negative values

### ISSUE THREAD

**Issue by shreejalt** [kemaloksuz/BoundingBoxGenerator#1]
Hi @kemaloksuz, 

I am having one issue while generating the bounding boxes. When I run the Bounding Box Generator script, it gives negative values of the generated bounding boxes given small values in the `inputBox`. For example when I pass input box coordinates as [0, 4, 100, 120](topleftx, toplefty, bottomrightx, bottomtighty) for the IoU list [0.5, 0.6, 0.7], it gives output as: 
`Tensor([[-13.2084,  -0.9354, 107.5733, 131.8864],
               [ 15.9043, -31.7901, 102.2719, 127.7687],
               [  1.7417,  31.2658, 102.0986, 124.3840]])`. 

Am I doing something wrong while passing the arguments to Bounding Box Generator?

I am initializing the Box Sampler class as

`generator= BoxSampler(RoINumber=1)`
and the using the function
`generator.BoundingBoxGenerator(inputBox, IoUSet, numBoxes)`

Also can you tell me what is the use of the argument `RoINumber` in `BoxSampler` class 
 
Here `inputBox = tensor([  0.,   4., 120., 110.])`,  ` IoUSet = [0.5, 0.6, 0.7]`,  `numBoxes = 3`

If you can guide me by giving some documentation or some steps to use your script, it would be very helpful. Thanks

**Comment by kemaloksuz** [comment]
Hi,

Bounding box generator itself does not care about the feasibility. You should correct the negative values by clamping/clipping after having the boxes from the generator. For example, generator.sample() makes all the necessary adjustments before and after generating the boxes via BB Generator but it is designed specifically for obj.det. I understand that this does not fit your purpose and you look for a more simplified version. 

So, after your request, I modified the code as follows:

1-I added sample_single() function to the BoxSampler class that should be the that you look for.

2-I created a demo to show how it works. Please run /demo/bounding_box_generator_demo.py script. 

3-Now you can initialize generator without RoINumber. Normally, in the obj.det. pipeline, you should tell how many boxes will be generated. That was RoINumber, but currently, you can drop it. Please see the demo I told above.

4-I also updated the code to current mmdetection version and provide documentation as comments in bounding_box_generator.py. 

If you have more questions, I am glad to answer.

Kemal

**Comment by shreejalt** [comment]
Hi @kemaloksuz, 
Thanks a lot. Yeah, I exactly wanted this function to go forward. Really wonderful algorithm designed. A simple mathematical explanation makes it very easy to understand code and also the paper.

Thanking you, 
Shreejal Trivedi
